keys:
  users:
    - &sspeaks age1ngm5476nk6y7vqqj0anwqsf3vr4yw6ppr0wn20prrp6zv96g4fuswqzrlv
  hosts:
    - &mbp age1m02wz3xqkg6z0fflpdhvph0psw0vavhdusz9lzg3daa5aammc5xsxtwzds
    - &nixpi age1nfquhf85wlt2ez7c4me0y8yqpcrnyn68vy7lkfu5tec873rad5gsmg2n3x
    - &nixosazure age1kw6rmz7v2v3p88tazheyv3a80ls55e2x8jy33svewu58q7w7gqzs2nuagp
    - &nixosWSLwork age1rq8j2df482hyksxcatvmvetcta9lkvuyhwz3h52037d7xele7udq24pe23
    - &nixosWSL age1tu7k447prh3229y00nq2makh6a6a5f9c558djm92amzyahnwvy9qa0jv3r
    - &asahi age1wdfa5rgtmpnf5v40gy0n0fr7sldjeqkqqgn74euqjy5nd4elq9asnfps6n
    - &nixpi5 age17gq4myuue6fq0n859svnzl9dt8s9dq2w3ax67tcq0lptsqsmceuqzyglp5
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *sspeaks
        - *mbp
        - *nixpi
        - *nixosazure
        - *nixosWSLwork
        - *nixosWSL
        - *asahi
        - *nixpi5

