keys:
  users:
    - &sspeaks age1ngm5476nk6y7vqqj0anwqsf3vr4yw6ppr0wn20prrp6zv96g4fuswqzrlv
  hosts:
    - &mbp age1m02wz3xqkg6z0fflpdhvph0psw0vavhdusz9lzg3daa5aammc5xsxtwzds
    - &nixpi age1nfquhf85wlt2ez7c4me0y8yqpcrnyn68vy7lkfu5tec873rad5gsmg2n3x
    - &nixosazure age1a04su9wxnvtzrs5kpjyhl22jzt56r0222xmzhr7pcsrdg5u7ze9qe38r29
    - &nixosWSLwork age1rq8j2df482hyksxcatvmvetcta9lkvuyhwz3h52037d7xele7udq24pe23
    - &nixosWSL age106k2pwqk6nvnenu0tc773l3uc9r07r4txxlq7nz8zky2t0uvp3lqy96vr4
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *sspeaks
        - *mbp
        - *nixpi
        - *nixosazure
        - *nixosWSLwork
        - *nixosWSL

