keys:
  users:
    - &sspeaks age1ngm5476nk6y7vqqj0anwqsf3vr4yw6ppr0wn20prrp6zv96g4fuswqzrlv
  hosts:
    - &mbp age1m02wz3xqkg6z0fflpdhvph0psw0vavhdusz9lzg3daa5aammc5xsxtwzds
    - &nixpi age1nfquhf85wlt2ez7c4me0y8yqpcrnyn68vy7lkfu5tec873rad5gsmg2n3x
    - &nixosazure age1kw6rmz7v2v3p88tazheyv3a80ls55e2x8jy33svewu58q7w7gqzs2nuagp
    - &nixosWSLwork age1rq8j2df482hyksxcatvmvetcta9lkvuyhwz3h52037d7xele7udq24pe23
    - &nixosWSL age1tu7k447prh3229y00nq2makh6a6a5f9c558djm92amzyahnwvy9qa0jv3r
    - &asahi age1wdfa5rgtmpnf5v40gy0n0fr7sldjeqkqqgn74euqjy5nd4elq9asnfps6n
    - &nixpi5 age1q9khmexesfhl56c4ste9ur59fdcyfauy728jvmzlay2nhvlz74ssvh784j
creation_rules:
  # Shared secrets: all hosts need these (user password, ssh key, etc.)
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
        - *sspeaks
        - *mbp
        - *nixpi
        - *nixosazure
        - *nixosWSLwork
        - *nixosWSL
        - *asahi
        - *nixpi5
  # Azure-only secrets (pogbot, wireguard server)
  - path_regex: secrets/nixos-azure\.yaml$
    key_groups:
      - age:
        - *sspeaks
        - *nixosazure
  # Nixpi-only secrets (wifi, wireguard client)
  - path_regex: secrets/nixpi\.yaml$
    key_groups:
      - age:
        - *sspeaks
        - *nixpi
  # Nixpi5-only secrets (authentik)
  - path_regex: secrets/nixpi5\.yaml$
    key_groups:
      - age:
        - *sspeaks
        - *nixpi5

