# Plate XIV shell, started by niri/config.kdl.nix.
# Keep systemd autostart disabled so it does not run in the Hyprland fallback.
# Manual preview: quickshell -c plate-xiv

{ lib, pkgs, ... }:

let
  plate = import ../theme/plate.nix;

  # Convert CSS px tokens to integers for QML numeric properties.
  stripPx = s: lib.toInt (builtins.replaceStrings [ "px" ] [ "" ] s);

  # Bridge plate.nix tokens to a singleton shared by the QML components.
  themeQml = pkgs.writeText "Theme.qml" ''
    pragma Singleton
    import QtQuick

    // Generated by home/features/quickshell/default.nix; do not edit directly.
    QtObject {
        // Background layers (darkest → lightest)
        readonly property color bgVoid:   "${plate.bg.void}"
        readonly property color bgBase:   "${plate.bg.plate}"
        readonly property color bgRaised: "${plate.bg.panel}"
        readonly property color bgFill:   "${plate.bg.inset}"

        // Foreground text hierarchy
        readonly property color fgPrimary:   "${plate.fg.primary}"
        readonly property color fgSecondary: "${plate.fg.secondary}"
        readonly property color fgMuted:     "${plate.fg.muted}"

        // Structural lines
        readonly property color lineHairline: "${plate.line.hairline}"
        readonly property color lineRule:     "${plate.line.rule}"
        readonly property color lineEdge:     "${plate.line.edge}"

        // Accent / state
        readonly property color accentPrimary: "${plate.accent.vermilion}"
        readonly property color accentOn:      "${plate.accent.on}"
        readonly property color stateFail:     "${plate.state.fail}"
        readonly property color stateFocus:    "${plate.state.focus}"

        // Caption reserves 28 logical pixels at the top of each screen.
        readonly property int captionHeight: 28
        readonly property int border:        ${toString (stripPx plate.geometry.border)}
        readonly property int spacingSm:     ${toString (stripPx plate.geometry.gap)}
        readonly property int spacingLg:     ${toString (stripPx plate.geometry.gapOuter)}

        // Typography
        readonly property string fontMono: "${plate.type.mono}"
        readonly property string fontTerm: "${plate.type.terminal}"
        readonly property string fontUi:   "${plate.type.mono}"
    }
  '';

  # Merge generated Theme.qml with the versioned QML sources.
  configDir = pkgs.symlinkJoin {
    name = "quickshell-plate-xiv";
    paths = [
      (pkgs.runCommand "plate-xiv-theme" { } ''
        mkdir -p "$out"
        cp ${themeQml} "$out/Theme.qml"
      '')
      ./plate-xiv
    ];
  };
in
{
  programs.quickshell = {
    enable = true;
    configs."plate-xiv" = configDir;
  };
}
