{ config, lib, pkgs, ... }:

let
  stepCaUrl = "https://sspeaks.net:8443";
  stepFingerprint = "e7f787f0402243aa0dc0327414d05ea3c75d63b1ca55a2869bc6c8261c4d85ce";
  stepRoot = ''
    -----BEGIN CERTIFICATE-----
    MIIBmDCCAT6gAwIBAgIRAOBK3DPM0vc+llGT4x7SCZQwCgYIKoZIzj0EAwIwKjEP
    MA0GA1UEChMGc2V0aGNhMRcwFQYDVQQDEw5zZXRoY2EgUm9vdCBDQTAeFw0yMTEy
    MDkxNzM4NTVaFw0zMTEyMDcxNzM4NTVaMCoxDzANBgNVBAoTBnNldGhjYTEXMBUG
    A1UEAxMOc2V0aGNhIFJvb3QgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATj
    t1CVz7DXSptM+SlHM94A9hAC9KtXzLj7CT5kE+DPXS8nn/NC0PcUUQfF7OrBooLm
    9S8mRvbMHko2gngwhMsCo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgw
    BgEB/wIBATAdBgNVHQ4EFgQUj0YVOP6238AiQHPThzzsSKJgUuMwCgYIKoZIzj0E
    AwIDSAAwRQIgWPFJ0juApdJohHlVE8LVr/4+Q/kwR2vXJivwI9pdNoICIQCjzsph
    RYy6VQsIe3s3tJ9XPHmkPhYZGSGyI+FKlEeTmA==
    -----END CERTIFICATE-----
  '';
  stepSshCaKey = "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBB8xhibytWe2DsrMCDrk59AxdtCdAsyjsSmFEz05ovXL2obJ2U1o10tv3tQAaNPMnBypE8LqRZGfklpjPSGyTq8=";
  stepIncludeBlock = ''
    # autogenerated by home-manager for step ssh
    Host *
        Include "${config.home.homeDirectory}/.step/ssh/includes"
    # end
  '';
in
{
  home.packages = [ pkgs.step-cli ];

  home.file.".step/certs/root_ca.crt" = {
    force = true;
    text = stepRoot;
  };
  home.file.".step/config/defaults.json" = {
    force = true;
    text = builtins.toJSON {
      ca-url = stepCaUrl;
      fingerprint = stepFingerprint;
      root = "${config.home.homeDirectory}/.step/certs/root_ca.crt";
    };
  };
  home.file.".step/ssh/includes" = {
    force = true;
    text = ''
      Include "${config.home.homeDirectory}/.step/ssh/config"
    '';
  };
  home.file.".step/ssh/config" = {
    force = true;
    text = ''
      Host sspeaks.net
          User sspeaks610

      Match exec "step ssh check-host %h"
          UserKnownHostsFile "${config.home.homeDirectory}/.step/ssh/known_hosts"
          ProxyCommand step ssh proxycommand %r %h %p --provisioner Google
    '';
  };
  home.file.".step/ssh/known_hosts" = {
    force = true;
    text = ''
      @cert-authority * ${stepSshCaKey}
    '';
  };

  home.activation.ensureStepSshInclude = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        ssh_config="${config.home.homeDirectory}/.ssh/config"
        mkdir -p "$(dirname "$ssh_config")"
        touch "$ssh_config"
        chmod 600 "$ssh_config"
        if ! grep -Fq '${config.home.homeDirectory}/.step/ssh/includes' "$ssh_config"; then
          {
            printf '\n'
            cat <<'EOF'
    ${stepIncludeBlock}
    EOF
          } >> "$ssh_config"
        fi
  '';
}
