name: Flake Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: disabled
          use-gha-cache: enabled

      - name: nix flake check
        run: nix flake check --show-trace --print-build-logs
